### ISSUE TITLE
Each instance has its own dataset?

### ISSUE THREAD

**Issue by inzanez** [cyon/vuex-pagination#1]
Hi

I've just been scanning through your code. Am I right that although there can be many instances for a single resource, all these instances will store there own data-set internally?

So multiple copies of the same data could be present in the store, assuming that I have two instances with the same page offset & size on the same resource?

**Comment by MaxGfeller** [comment]
Hi @inzanez!

There can be many instances on a single resource and as long as they use no (or the same) `args` the data-set is being only kept once.

The getter function for the instance retrieves the desired items from the data-set (or registry as we call it): https://github.com/cyon/vuex-pagination/blob/master/src/createResource.js#L44.

That means the same data will usually not have to be fetched twice.

**Comment by MaxGfeller** [comment]
@inzanez Exactly!

**Comment by inzanez** [comment]
@MaxGfeller
Finally gone through your implementation to the full extent. Congratulations, this is really inspiring. I will try to combine that with JsonAPI specifications...:-)

**Comment by MaxGfeller** [comment]
@inzanez Sweet, let me know if you need help :)
