### ISSUE TITLE
Unexpected error when using component data as page argument

### ISSUE THREAD

**Issue by danielbachhuber** [cyon/vuex-pagination#22]
Hi 👋 

Thanks for the great library 😄 

I see an unexpected "Uncaught TypeError: undefined has no properties" error when I use component data as the `page` argument:

```js
items: createInstance('items', {
    page: this.initialPage,
    args() {
        return {
            order: 'desc',
        };
    }
}),
```

Is this expected?

**Comment by MaxGfeller** [comment]
Hi @danielbachhuber!

This unfortunately doesn't work as the `createInstance` method is called before the component itself is initialized. What you can do is to initialize it to `1` (or anything, really) and in the `beforeMount` hook set `this.items.page` to `this.initialPage`.

**Comment by danielbachhuber** [comment]
Thanks for the reply, @MaxGfeller 😄 

> What you can do is to initialize it to `1` (or anything, really) and in the `beforeMount` hook set `this.items.page` to `this.initialPage`.

Hm, this doesn't seem to work either:

```js
beforeMount() {
    let url = new URL(window.location.href);
    this.items.page = url.searchParams.get('page') || 1;
},
```

I'm relatively new at Vue, so let me know if there's some obvious mistake...

**Comment by danielbachhuber** [comment]
As it turns out, the `created()` hook works fine:

```js
created() {
    let url = new URL(window.location.href);
    this.items.page = url.searchParams.get('page') || 1;
},
```
