### ISSUE TITLE
IE11

### ISSUE THREAD

**Issue by wirk** [cyon/vuex-pagination#6]
Thanks for the great plugin. Is this supposed to work in IE11? I am getting an "Identifier expected" error. 

/*!***********************************************!*\
  !*** ./node_modules/vuex-pagination/index.js ***!
  \***********************************************/
/*! no static exports found */
/***/ (function(module, exports, __webpack_require__) {

If I add the plugin to the transpileDependencies array, I get an error in Chrome as well:
> Uncaught TypeError: Cannot assign to read only property 'exports' of object '#<Object>'

**Comment by MaxGfeller** [comment]
This module unfortunately **does not** work with IE11. It makes heavy use of the [`Proxy`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) API which is [not supported](https://caniuse.com/#search=proxy) by Internet Explorer.
